# Generated by Django 5.2.14 on 2026-05-31 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_booking_created_at_booking_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available_rooms',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='RoomBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('maintenance', 'Maintenance'), ('renovation', 'Renovation'), ('closed', 'Closed')], max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.room')),
            ],
        ),
    ]
